#!/bin/sh

if [ -z "${1+deez}" ]; then
    echo fuck you >&2
    exit 1
fi

# Arbitrary but unique message tag
msgTag="myvolume"

# Changing system volume
if [ "$1" = mute ]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
else
    pactl set-sink-volume @DEFAULT_SINK@ "$1"
fi

# Query amixer for the current volume and whether or not the speaker is muted
volume_string="$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR == 1{print $5"/"$12}')"
volume=$(printf '%s\n' "$volume_string" | sed 's/\// + /;s/%//g;s/$/ ) \/ 2/;s/^/( /' | xargs expr)
mute="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"
if [ "$mute" = "yes" ]; then
    # Show the sound muted notification
    dunstify -a "volume-control" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" 
else
    # Show the volume notification
    dunstify -a "volume-control" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "󰕾  ${volume_string}"
fi

# Play the volume changed sound
aplay -t wav ~/Sounds/EarthBound\ Status\ Sounds/notification.wav &

